### PR TITLE
Eve

### PR DESCRIPTION
**Pull request by fangyi-zhou**

### CODE REVIEW

**Review by egnwd — CHANGES_REQUESTED** [review]
Hi, thanks for the submission! Would you be able to provide some more details about the project: what is the end result (web app, app etc.), Some links to the original project for people to look at if possible?

**Comment by fangyi-zhou** [comment]
https://gitlab.doc.ic.ac.uk/pk3115/LabStalker

**Comment by fangyi-zhou** [comment]
@faboor

**Comment by fangyi-zhou** [comment]
updated

**Comment by fangyi-zhou** [comment]
ping

**Comment by fangyi-zhou** [comment]
Hi. We'll consider moving the project to github after our first release. Thanks

**Pull request closed without merging**
